---
version: "2.1"
services:
  flaresolverr:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - VNC_PASSWORD=${VNC_PASSWORD:-none}
      - TZ=Europe/Moscow
    volumes:
      - ./src:/app/flaresolverr
      - ./ContainerData/Downloads:/app/Downloads
      - ./ContainerData/ChromeProfile:/app/ChromeProfile
      - ./ContainerData/hosts:/etc/hosts
    ports:
      - "${PORT:-8191}:8191"
      - "5900:5900"
    restart: unless-stopped
